/** 이미지가 준비되면 빈 문자열만 실제 파일 경로로 교체한다. */
export const GAME_ASSETS = Object.freeze({
  titleBackground: new URL("../assets/images/title-background.png", import.meta.url).href,
  roomBackgrounds: {
    chapter1: new URL("../assets/images/forest-wall.png", import.meta.url).href,
    chapter2: "",
    chapter3: "",
  },
  rock: new URL("../assets/images/rock.png", import.meta.url).href,
  campfire: new URL("../assets/images/campfire-logs.png", import.meta.url).href,
  player: new URL("../assets/images/player-world.png", import.meta.url).href,
  faces: Object.freeze({
    player: new URL("../assets/images/player-face.png", import.meta.url).href,
    playerInjured: new URL("../assets/images/player-face-injured.png", import.meta.url).href,
    npc: new URL("../assets/images/npc-face.png", import.meta.url).href,
  }),
  entities: Object.freeze({
    "npc.guide": new URL("../assets/images/npc-world.png", import.meta.url).href,
    "monster.slime.normal": new URL("../assets/images/slime-normal.png", import.meta.url).href,
    "monster.slime.grass": new URL("../assets/images/slime-grass.png", import.meta.url).href,
    "monster.slime.fire": new URL("../assets/images/slime-fire.png", import.meta.url).href,
    "monster.slime.water": new URL("../assets/images/slime-water.png", import.meta.url).href,
    "monster.big-slime.normal": new URL("../assets/images/slime-normal.png", import.meta.url).href,
    "monster.big-slime.grass": new URL("../assets/images/slime-grass.png", import.meta.url).href,
    "monster.big-slime.fire": new URL("../assets/images/slime-fire.png", import.meta.url).href,
    "monster.big-slime.water": new URL("../assets/images/slime-water.png", import.meta.url).href,
    "monster.warrior-spirit.normal": new URL("../assets/images/warrior-spirit-normal.png", import.meta.url).href,
    "monster.warrior-spirit.grass": new URL("../assets/images/warrior-spirit-grass.png", import.meta.url).href,
    "monster.warrior-spirit.fire": new URL("../assets/images/warrior-spirit-fire.png", import.meta.url).href,
    "monster.warrior-spirit.water": new URL("../assets/images/warrior-spirit-water.png", import.meta.url).href,
    "monster.mage-spirit.normal": new URL("../assets/images/mage-spirit-normal.png", import.meta.url).href,
    "monster.mage-spirit.grass": new URL("../assets/images/mage-spirit-grass.png", import.meta.url).href,
    "monster.mage-spirit.fire": new URL("../assets/images/mage-spirit-fire.png", import.meta.url).href,
    "monster.mage-spirit.water": new URL("../assets/images/mage-spirit-water.png", import.meta.url).href,
    "monster.fairy.normal": new URL("../assets/images/fairy-normal.png", import.meta.url).href,
    "monster.fairy.grass": new URL("../assets/images/fairy-grass.png", import.meta.url).href,
    "monster.fairy.fire": new URL("../assets/images/fairy-fire.png", import.meta.url).href,
    "monster.fairy.water": new URL("../assets/images/fairy-water.png", import.meta.url).href,
    "monster.spirit-king": new URL("../assets/images/boss-spirit-king.png", import.meta.url).href,
    "monster.mini-golem": "",
    "monster.golem": "",
    "monster.electric-snake": "",
    "monster.ice-bat": "",
    "monster.dark-knight": "",
    "monster.dark-mage": "",
    "monster.imp": "",
    "monster.demon": "",
  }),
});
